export default[
    {
      "login": "shayan-taheri",
      "id": 29395458,
      "node_id": "MDQ6VXNlcjI5Mzk1NDU4",
      "avatar_url": "https://avatars.githubusercontent.com/u/29395458?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/shayan-taheri",
      "html_url": "https://github.com/shayan-taheri",
      "followers_url": "https://api.github.com/users/shayan-taheri/followers",
      "following_url": "https://api.github.com/users/shayan-taheri/following{/other_user}",
      "gists_url": "https://api.github.com/users/shayan-taheri/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/shayan-taheri/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/shayan-taheri/subscriptions",
      "organizations_url": "https://api.github.com/users/shayan-taheri/orgs",
      "repos_url": "https://api.github.com/users/shayan-taheri/repos",
      "events_url": "https://api.github.com/users/shayan-taheri/events{/privacy}",
      "received_events_url": "https://api.github.com/users/shayan-taheri/received_events",
      "type": "User",
      "site_admin": false
    },
    {
      "login": "bestsaifali",
      "id": 48447440,
      "node_id": "MDQ6VXNlcjQ4NDQ3NDQw",
      "avatar_url": "https://avatars.githubusercontent.com/u/48447440?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/bestsaifali",
      "html_url": "https://github.com/bestsaifali",
      "followers_url": "https://api.github.com/users/bestsaifali/followers",
      "following_url": "https://api.github.com/users/bestsaifali/following{/other_user}",
      "gists_url": "https://api.github.com/users/bestsaifali/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/bestsaifali/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/bestsaifali/subscriptions",
      "organizations_url": "https://api.github.com/users/bestsaifali/orgs",
      "repos_url": "https://api.github.com/users/bestsaifali/repos",
      "events_url": "https://api.github.com/users/bestsaifali/events{/privacy}",
      "received_events_url": "https://api.github.com/users/bestsaifali/received_events",
      "type": "User",
      "site_admin": false
    },
    {
      "login": "smriti1823",
      "id": 64310192,
      "node_id": "MDQ6VXNlcjY0MzEwMTky",
      "avatar_url": "https://avatars.githubusercontent.com/u/64310192?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/smriti1823",
      "html_url": "https://github.com/smriti1823",
      "followers_url": "https://api.github.com/users/smriti1823/followers",
      "following_url": "https://api.github.com/users/smriti1823/following{/other_user}",
      "gists_url": "https://api.github.com/users/smriti1823/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/smriti1823/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/smriti1823/subscriptions",
      "organizations_url": "https://api.github.com/users/smriti1823/orgs",
      "repos_url": "https://api.github.com/users/smriti1823/repos",
      "events_url": "https://api.github.com/users/smriti1823/events{/privacy}",
      "received_events_url": "https://api.github.com/users/smriti1823/received_events",
      "type": "User",
      "site_admin": false
    },
    {
      "login": "Sagar100699",
      "id": 66002380,
      "node_id": "MDQ6VXNlcjY2MDAyMzgw",
      "avatar_url": "https://avatars.githubusercontent.com/u/66002380?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/Sagar100699",
      "html_url": "https://github.com/Sagar100699",
      "followers_url": "https://api.github.com/users/Sagar100699/followers",
      "following_url": "https://api.github.com/users/Sagar100699/following{/other_user}",
      "gists_url": "https://api.github.com/users/Sagar100699/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/Sagar100699/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/Sagar100699/subscriptions",
      "organizations_url": "https://api.github.com/users/Sagar100699/orgs",
      "repos_url": "https://api.github.com/users/Sagar100699/repos",
      "events_url": "https://api.github.com/users/Sagar100699/events{/privacy}",
      "received_events_url": "https://api.github.com/users/Sagar100699/received_events",
      "type": "User",
      "site_admin": false
    },
    {
      "login": "Mudit-Thakral",
      "id": 66005451,
      "node_id": "MDQ6VXNlcjY2MDA1NDUx",
      "avatar_url": "https://avatars.githubusercontent.com/u/66005451?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/Mudit-Thakral",
      "html_url": "https://github.com/Mudit-Thakral",
      "followers_url": "https://api.github.com/users/Mudit-Thakral/followers",
      "following_url": "https://api.github.com/users/Mudit-Thakral/following{/other_user}",
      "gists_url": "https://api.github.com/users/Mudit-Thakral/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/Mudit-Thakral/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/Mudit-Thakral/subscriptions",
      "organizations_url": "https://api.github.com/users/Mudit-Thakral/orgs",
      "repos_url": "https://api.github.com/users/Mudit-Thakral/repos",
      "events_url": "https://api.github.com/users/Mudit-Thakral/events{/privacy}",
      "received_events_url": "https://api.github.com/users/Mudit-Thakral/received_events",
      "type": "User",
      "site_admin": false
    }
  ]