export default {
login: "vinitpulstya",
id: 64360977,
node_id: "MDQ6VXNlcjY0MzYwOTc3",
avatar_url: "https://avatars0.githubusercontent.com/u/64360977?v=4",
gravatar_id: "",
url: "https://api.github.com/users/vinitpulstya",
html_url: "https://github.com/vinitpulstya",
followers_url: "https://api.github.com/users/vinitpulstya/followers",
following_url: "https://api.github.com/users/vinitpulstya/following{/other_user}",
gists_url: "https://api.github.com/users/vinitpulstya/gists{/gist_id}",
starred_url: "https://api.github.com/users/vinitpulstya/starred{/owner}{/repo}",
subscriptions_url: "https://api.github.com/users/vinitpulstya/subscriptions",
organizations_url: "https://api.github.com/users/vinitpulstya/orgs",
repos_url: "https://api.github.com/users/vinitpulstya/repos",
events_url: "https://api.github.com/users/vinitpulstya/events{/privacy}",
received_events_url: "https://api.github.com/users/vinitpulstya/received_events",
type: "User",
site_admin: false,
name: "pulstya",
company: null,
blog: "",
location: "India",
email: null,
hireable: true,
bio: "Officially named Vinit Sharma. Tech enthusiast, HDL learner. ",
twitter_username: null,
public_repos: 3,
public_gists: 0,
followers: 4,
following: 5,
created_at: "2020-04-26T12:35:48Z",
updated_at: "2020-12-23T12:19:45Z"
};
